### ISSUE TITLE
Omni-C support ?

### ISSUE THREAD

**Issue by amvarani** [zengxiaofei/HapHiC#10]
The Omni-C data is supported by HapHiC ?

**Comment by zengxiaofei** [comment]
Hi @amvarani,

Although I have not tested Omni-C data for HapHiC scaffolding yet, but I think it should be compatible. Using the default `--RE GATC` is fine, since this parameter has only little impact on the anchoring rate.

Best regards,
Xiaofei

**Comment by amvarani** [comment]
Thanks @zengxiaofei 

I have been testing HapHiC on a hexaploid plant genome. K-mer analysis indicates a pattern resembling AAAAAB in an assembled genome of 9.8Gb (N50 of 22Mb - largest contig 146mb). This means that I expect 1.6Gb per haplotype.

Do you have any tips for running HapHiC?"
