### ISSUE TITLE
Error: died with <Signals.SIGKILL: 9

### ISSUE THREAD

**Issue by Zhenlisme** [zengxiaofei/HapHiC#13]
Hello Xiaofei,

I could not go through the haphic pipeline with this command `haphic pipeline scaffolds.ref.fa HiC.filtered.bam 20 --RE GATC,GANTC,CTNAG,TTAA --correct_nrounds 2 --remove_allelic_links 4 --threads 20 --processes 8`. I encountered this error message:
```
Traceback (most recent call last):
  File "/home/li/bioinfo/HapHiC/haphic", line 96, in <module>
    subprocess.run(commands, check=True)
  File "/home/li/miniforge3/envs/haphic/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/li/bioinfo/HapHiC/scripts/HapHiC_pipeline.py', 'scaffolds.ref.fa', 'HiC.filtered.bam', '20', '--RE', 'GATC,GANTC,CTNAG,TTAA', '--correct_nrounds', '2', '--remove_allelic_links', '4', '--threads', '20', '--processes', '8']' died with <Signals.SIGKILL: 9>.

```
Could you please give me any suggestions?
Thank you for your time.
Zhen

**Comment by zengxiaofei** [comment]
Hi Zhen,

This error message indicates that your task was killed. The reason for this termination is uncertain, as it could be done by anyone with the authority (`kill -9 <pid>`). If the task was not killed by yourself or a superuser, then it is possible that the task exceeded the memory limit. If you are using a job scheduling system such as PBS or SLURM, you can trace the maximum memory usage by using the corresponding command (e.g., `tracejob <jobid>` for PBS and `sacct -j <jobid> --long` for SLURM).

If it's indeed a memory issue, and the pipeline was terminated during the execution of step 3 (the `03.sort` directory was created but `04.build` was not), you may consider reducing the number of processes (e.g., use --processes 4). Alternatively, you could run the pipeline on a server with higher memory capacity.

Best regards,
Xiaofei

**Comment by Zhenlisme** [comment]
Hello Xiaofei,

Thank you for your quick reply. 
It seems to be a memory issue. But I only have one directory (01.cluster). I will try to reduce the process number and rerun it.

All the best,
Zhen

**Comment by Zhenlisme** [comment]
Thank you for your information!
