### ISSUE TITLE
The question about regenerating a HiC contact map for the final assembly 

### ISSUE THREAD

**Issue by qdu-beep** [zengxiaofei/HapHiC#14]
Hello developer,

After successfully running the Step1 and Step2, I got the two files ( **out_JBAT.FINAL.agp** and **out_JBAT.FINAL.fa**). I want to regenerate a .hic file corresponding to the final assembly. I'm not sure if the input files I chose to complete the Step 3 are correct ( **the original BED/BAM file**, **contigs.fa.fai**, **out_JBAT.FINAL.agp** and **out_JBAT.FINAL.fa.chrom.sizes**). I would be very grateful if you could provide some help! my commands are as follows.

### Step1.  juicerbox.sh
/software/HapHiC/scripts/../utils/juicer pre -a -q 1 -o out_JBAT samblasterHiCfilter2.bed scaffolds.raw.agp **asm.fa.fai** >out_JBAT.log 2>&1
(java -jar -Xmx32G /software/HapHiC/scripts/../utils/juicer_tools.1.9.9_jcuda.0.8.jar pre out_JBAT.txt out_JBAT.hic.part <(cat out_JBAT.log | grep PRE_C_SIZE | awk '{print $2" "$3}')) && (mv out_JBAT.hic.part out_JBAT.hic)

### Step2. After adjusting in juicerbox
/software/HapHiC/scripts/../utils/juicer post -o out_JBAT out_JBAT.review.assembly out_JBAT.liftover.agp **asm.fa**

### Step3. Regenerating a HiC contact map for the final assembly
(/software/HapHiC/scripts/../utils/juicer pre **samblasterHiCfilter2.bed** **out_JBAT.FINAL.agp asm.fa.fai** | sort -k2,2d -k6,6d -T ./ --parallel=8 -S32G | awk 'NF' > alignments_sorted.txt.part) && (mv alignments_sorted.txt.part alignments_sorted.txt)

(java -jar -Xmx32G /software/HapHiC/scripts/../utils/juicer_tools.1.9.9_jcuda.0.8.jar pre alignments_sorted.txt out.hic.part **out_JBAT.FINAL.fa.chrom.sizes**) && (mv out.hic.part out.hic)

**Comment by zengxiaofei** [comment]
Hi Patrick,

I have provided a detailed example in another issue #8. You may check it out.

Best regards,
Xiaofei

**Comment by qdu-beep** [comment]
> Hi Patrick,
> 
> I have provided a detailed example in another issue #8. You may check it out.
> 
> Best regards, Xiaofei

Hello Xiaofei,

Many thanks for your help! 

Best regards,
Qiao
