### ISSUE TITLE
Correct way to run HapHiC with Hifiasm (HiC) data

### ISSUE THREAD

**Issue by RunpengLuo** [zengxiaofei/HapHiC#16]
Dear Developer,

Thank you your effort on developing the HapHiC,

I have a Hifiasm (hiC) data with both (hap1.p_ctg.gfa and hap2.p_ctg.gfa), I noticed that at the Section `Work with hifiasm (experimental)` there is a recommended command.

```
/path/to/HapHiC/haphic pipeline allhaps.fa HiC.filtered.bam nchrs --gfa "hap1.p_ctg.gfa,hap2.p_ctg.gfa"
```

The species I'm working on is diploid and having 33 chromosomes, I merged both hap1.p_ctg.gfa and hap2.p_ctg.gfa and leads to a single FASTA file as `allhaps.fa`, and use `nchrs=66`.  (from #1 )

I just would like to confirm if it is the correct way for handling the data from hifiasm (hic). Thanks a lot for your support!

Best wishes,
Runpeng Luo

**Comment by zengxiaofei** [comment]
Hi Runpeng,

Yes, you are correct. When the heterozygosity of the diploid genome is sufficient, this may be the best way to scaffold your assembly. However, in the case of low heterozygosity, the criteria `MAPQ > 0` may filter out a significant number of Hi-C links, you need to scaffold each haplotype individually.

Best regards,
Xiaofei

**Comment by RunpengLuo** [comment]
Thanks a lot for your quick response Xiaofei, it was really helpful. I'll try scaffold them individually as well and compare with the mixed one. Hope you have a nice day!
