### ISSUE TITLE
Question regarding Trio Binning files 

### ISSUE THREAD

**Issue by carolhsb** [zengxiaofei/HapHiC#17]
Hi,

I am working with Trio Binning data, and I am wondering which hifiasm output I should use in HapHiC.

I concatenated hap1(.dip.hap1.p_ctg.fa) and hap2 (.dip.hap2.p_ctg.fa) contigs into a single file to use as HapHiC input. 

Is that the best strategy?

Thank you in advance,

Carolina

**Comment by zengxiaofei** [comment]
Hi Carolina,

Your question is quite similar to #16, and the answer is also suitable:

> When the heterozygosity of the diploid genome is sufficient, this may be the best way to scaffold your assembly. However, in the case of low heterozygosity, the criteria MAPQ > 0 may filter out a significant number of Hi-C links, you need to scaffold each haplotype individually.

Best regards,
Xiaofei

**Comment by carolhsb** [comment]
Dear @zengxiaofei 

Thanks for the quick reply!

As the individual I am working with is a hybrid, I will keep the strategy.

Best regards,
Carolina
