### ISSUE TITLE
N region in plot

### ISSUE THREAD

**Issue by xiekunwhy** [zengxiaofei/HapHiC#18]
Hi,

I found that haphic plot deal with signal in N region in a wrong way,

here is haphic plot (N region is so heat), 
![image](https://github.com/zengxiaofei/HapHiC/assets/17738229/5147bf8a-7c30-48b9-aa56-7be1d207d7a2)

it should be
![image](https://github.com/zengxiaofei/HapHiC/assets/17738229/a1f4eaa5-deed-46bd-9599-0ce11403c654)

Heat signal in N region may misleading readers some times, I think.

Best,
Kun

**Comment by zengxiaofei** [comment]
Hi Kun,

This issue may be raised by KR normalization. Could you please try using the parameter `--normalization none` ?

Best regards,
Xiaofei

**Comment by xiekunwhy** [comment]
Hi Xiaofei,

Yes, the heat signal in N region disappeared when using parameter --normalization none.

Best,
Kun

**Comment by zengxiaofei** [comment]
I'll fix the problem soon. Thanks!

**Comment by xiekunwhy** [comment]
By the way, log10 normalization seem not work well for my data, do you know why?

KR
![image](https://github.com/zengxiaofei/HapHiC/assets/17738229/66051019-57d9-4e57-aab6-f2ebec493a3c)

none
![image](https://github.com/zengxiaofei/HapHiC/assets/17738229/f27b0863-861e-42de-8af2-316d2ad09fee)

log10
![image](https://github.com/zengxiaofei/HapHiC/assets/17738229/e810f94d-381c-46d8-888e-a06e673bdc39)

Best,
Kun

**Comment by zengxiaofei** [comment]
This phenomenon is quite normal. Log10 compresses the range of Hi-C links, causing the interaction intensity within chromosomes to resemble the interaction intensity between chromosomes. In general, it is not recommended to use Log10 for normalization purposes.

**Comment by xiekunwhy** [comment]
I see, thank very much.

**Comment by zengxiaofei** [comment]
I have fixed this bug in the [latest commit](https://github.com/zengxiaofei/HapHiC/commit/8d7035a25b9d8a57ab1ee61acdca0931e9c6cdad), you could give it a try. Thanks again!

**Comment by xiekunwhy** [comment]
It is OK now. You can close this issue as the bug has been fixed.
