### ISSUE TITLE
How to define the nchr for the pipeline

### ISSUE THREAD

**Issue by chenzixi07** [zengxiaofei/HapHiC#19]
Hello HapHiC developers,

I am handling a species with ~46 chromosomes.According to our previous HiC result, this species seems to be a Triploid.
However, we also found that some clusters maybe diploid on the HiC heatmap. We are not quite sure at this moment.
So, how should I define the 'nchr' while run the HapHiC pipeline？Should I use 46*3=138？

Regards,
Zixi

**Comment by zengxiaofei** [comment]
Hi Zixi,

I'm not quite sure about your description. If `46` is the haploid chromosome number, and your genome assembly is haplotype-phased (e.g., p_utg or catenated hap*.p_ctg), the `nchr` parameter should be set to 46 * 3 = 138.

Best,
Xiaofei

**Comment by chenzixi07** [comment]
Thanks for your reply, I will try.
