### ISSUE TITLE
How to add/remove elements to a haphic plot?

### ISSUE THREAD

**Issue by zhengyanstu** [zengxiaofei/HapHiC#20]
Hello, @zengxiaofei
Thank you for developing this software.
I am new to Haphic and have some questions about the plot function.I ran the following command: haphic plot out_JBAT.assembly.agp HiC.filtered.bam --bin_size 500 --min_len 5 --normalization log10 --border_style outline &
The generated plot is attached.
![1](https://github.com/zengxiaofei/HapHiC/assets/126577500/ff5eb56d-c24e-4cd6-9153-965b99d8ce5e)
I am wondering how to generate a plot with group information on the y-axis, similar to the example you provided.
Thank you for your help.

**Comment by zengxiaofei** [comment]
Hi @zhengyanstu,

You need to input `out_JBAT.FINAL.agp` instead of `out_JBAT.assembly.agp`. And I always recommend using KR normalization rather than log10.

Best regrads,
Xiaofei

**Comment by zhengyanstu** [comment]
> Hi @zhengyanstu,
> 
> You need to input `out_JBAT.FINAL.agp` instead of `out_JBAT.assembly.agp`. And I always recommend using KR normalization rather than log10.
> 
> Best regrads, Xiaofei

Thanks for your reply.
I generated out_JBAT.hic and out_JBAT.assembly using 'bash juicebox.sh' in the 04_build directory. After export them to Juicebox, I found that the original assembly results were good, so I just chose the out_JBAT.assembly.agp. Do I need to modify the sequence names when using Juicebox to import a reviewed assembly file and then use Juicer to generate an agp file?(If I want to set the scaffold name)
I chose KR normalization at the beginning, but the background of the plot was too cluttered. Is there any way to solve this?
![image](https://github.com/zengxiaofei/HapHiC/assets/126577500/51ceeed8-a641-4515-9117-622588e61d95)

**Comment by zengxiaofei** [comment]
> After export them to Juicebox, I found that the original assembly results were good, so I just chose the out_JBAT.assembly.agp.

If you want to visualize the original scaffolding result, you should choose `scaffolds.raw.agp`, not `out_JBAT.assembly.agp`.

> Do I need to modify the sequence names when using Juicebox to import a reviewed assembly file and then use Juicer to generate an agp file.

You can modify the first column in `scaffolds.raw.agp` to change the scaffold names, or modify the texts in a PDF editor (e.g., Adobe Illustrator).

> I chose KR normalization at the beginning, but the background of the plot was too cluttered.

It's a color range issue, which is controlled by two parameters, `--vmax_coef` and `--manual_vmax`. You can manually adjust them to achieve a better heatmap. Setting `--manual_vmax 0.01` may be suitable for your case.
