### ISSUE TITLE
Juicerbox YaHS

### ISSUE THREAD

**Issue by tianjio** [zengxiaofei/HapHiC#3]
Hi xiaofei,
 I used the Juicerbox YaHS you provided to generate the .assembly and .hic files, and finally generated out_JBAT.assembly ，out_JBAT.assembly.agp and out_JBAT.hic. However, I found that the generated out_JBAT.assembly.agp file has only one assembly, which cannot be divided into multiple assemblies, but his previous input file can be divided into multiple groups, and the corresponding contig and Chr frames cannot be displayed when input into juicerbox with .assemly and .hic. I would like to ask how to solve this problem.

**Comment by zengxiaofei** [comment]
Hi Tianjio,

In brief, please just ignore the file `out_JBAT.assembly.agp` generated by `juicer pre`. 

If you would like to visualize the scaffolding result with `haphic plot`, please use `scaffolds.raw.agp`.

For visualization and curation in Juicebox, please use the files `out_JBAT.assembly` and `out_JBAT.hic` instead. After manual curation in Juicebox, a new assembly file named `out_JBAT.review.assembly` will be obtained. You can use `juicer post` to generate the final AGP file `out_JBAT.FINAL.agp` and FASTA file `out_JBAT.FINAL.fa`: `juicer post -o out_JBAT out_JBAT.review.assembly out_JBAT.liftover.agp asm.fa`. Finnaly, utilize `out_JBAT.FINAL.agp` for `haphic plot`

Best regards,
Xiaofei
