### ISSUE TITLE
Why is there only one cluster in the HapHiC_cluster.log

### ISSUE THREAD

**Issue by zhangmeng123456abc** [zengxiaofei/HapHiC#31]
Hello Xiaofei,
Thank you for developing the Haphic software. my  HapHiC_cluster.log have a question "<HapHiC_cluster.py> [run_mcl_clustering] The maximum number of clusters (1) is even less than the expected number of chromosomes (16). You could try higher inflation. "  In this case, how to choose the "best" inflation recommendation

Thank you

**Comment by zengxiaofei** [comment]
Hi @zhangmeng123456abc,
I need more information to understand the problem:
(1) Your commands and parameters used in running HapHiC.
(2) Please upload the whole log file generated in 01.cluster
(3) Please calculate the N10-N90 and L10-L90 of the contigs input into HapHiC using [this tool](https://github.com/user-attachments/files/15572338/fa_detail.gz):
```bash
$ gunzip fa_detail.gz
$ chmod 755 fa_detail
$ fa_detail asm.fa
```
Best,
Xiaofei

**Comment by zhangmeng123456abc** [comment]
Hi Xiaofei,
(1)My commands and parameters used in running HapHiC: 0.bwa index asm.fa  
1. bwa mem -5SP -t 28 genome.final.fasta  hic.R1.fastq.gz  hic.R2.fastq.gz | samblaster | samtools view - -@ 14 -S -h -b -F 256 -o HiC.bam   2. HapHic/HapHiC-main/utils/filter_bam HiC.bam 1 --nm 3 --threads 14 | samtools view - -b -@ 14 -o HiC.filtered.bam  3.  HapHic/HapHiC-main/haphic cluster genome.final.fasta HiC.filtered.bam 16 
(2)  The log has been uploaded    
[HapHiC_cluster.log](https://github.com/user-attachments/files/15837566/HapHiC_cluster.log)
 (3) I can't run fa detail , I use assembly-stats for N50 statistics
sum = 442473677, n = 160, ave = 2765460.48, largest = 18480413
N50 = 9527079, n = 16
N60 = 7213451, n = 22
N70 = 5827328, n = 28
N80 = 4039110, n = 37
N90 = 2302510, n = 51
N100 = 29644, n = 160
N_count = 0
Gaps = 0

**Comment by zengxiaofei** [comment]
First, the FLAG filtering criterion you used is `-F 256`. This is incorrect. Supplementary alignments should be removed to make the BAM file suitable for HapHiC. Please use the criteria `-F 3340` that we recommended in [README.md](https://github.com/zengxiaofei/HapHiC?tab=readme-ov-file#align).
After making this modification, if you still encounter this error message, please try a higher inflation upper limit using the `--max_inflation` parameter (e.g., `--max_inflation 10`). A lower `--bin_size` may also helpful (e.g., `--bin_size 200`).
