### ISSUE TITLE
Parameter for output directory

### ISSUE THREAD

**Issue by tbenavi1** [zengxiaofei/HapHiC#33]
Hello, can you add a parameter for the output directory? Right now, HapHiC outputs everything in the current working directory. This will lead to problems if trying to run HapHiC on several samples from the same working directory. Thanks for your assistance.

**Comment by zengxiaofei** [comment]
Yes, I will have this function completed by the end of this week.

**Comment by zengxiaofei** [comment]
I have completed this function. Please use the `--outdir` parameter of `haphic pipeline` in the latest commit.

**Comment by wjq1981** [comment]
Any interest in adding output parameters to the "plot"? I find the generated Hi-C heatmaps very nice!
