### ISSUE TITLE
 the final number of groups was smaller than the nchrs I set.

### ISSUE THREAD

**Issue by YanChunL** [zengxiaofei/HapHiC#35]
A problem I had when using haphic occurred with both my tetraploid waxapple data and a simulated triploid data. When I used the default parameters, the final number of groups was smaller than the nchrs I set. When I modify the value of inflation to the recommended value in HapHiC_cluster.log, I find that the number of groups is still smaller than nchrs, and even when I continue to increase the value of inflation, the number of groups will show a trend of decline.But,as the value of inflation increases, the number of groups in the folder /inflation_X also increases
My commands：

bwa index ../00.data/asm.fa
bwa mem -5SP -t 32 ../00.data/asm.fa ../00.data/mockTriploid_r1.fq.gz ../00.data/mockTriploid_r2.fq.gz | samblaster | samtools view - -@ 32 -S -h -b -F 3340 -o HiC.bam
/HapHiC/utils/filter_bam HiC.bam 1 --nm 3 --threads 32 | samtools view - -b -@ 32 -o HiC.filtered.bam

/HapHiC/haphic cluster ../../00.data/asm.fa ../HiC.filtered.bam 36 --max_inflation 10.0 --remove_allelic_links 3
/HapHiC/haphic reassign ../00.data/asm.fa full_links.pkl ./inflation_5.0/mcl_inflation_5.0.clusters.txt paired_links.clm --nclusters 36

**Comment by zengxiaofei** [comment]
Some aspects that require further clarification or additional information:
(1) Were the Hi-C data and the assembly obtained from the same individual? (tetraploid waxapple)
(2) What methods (assembler and parameters) were used for genome assembly? Which assembly version was used for scaffolding (p_utg, p_ctg, or hap*.p_ctg)? Is the heterozygosity level of the genome sufficient for haplotype-phased assembly? (tetraploid waxapple)
(3) How was data simulated for the triploid genome? Whether both the assembly and Hi-C reads simulated? What is the heterozygosity level of the simulated assembly? Which tool was used for Hi-C read simulation (e.g., sim3C)? Please provide details of the commands used.

**Comment by zengxiaofei** [comment]
A straightforward way to determine what happened is by using the `--quick_view` mode and visualizing them in Juicebox (please refer to: https://github.com/zengxiaofei/HapHiC?tab=readme-ov-file#quick_view). This mode does not need a prior assumption of chromosome numbers.

**Comment by YanChunL** [comment]
（1：tetraploid waxapple）the Hi-C data and the assembly obtained is not from the same individual，The original sequencing data is CLR and the conting (default parameter) assembled by flye is used for scaffolding. Its heterozygosity should support typing. I use ONT (flye) and HiFi (utg) data for scaffolding. At the beginning, the group quantity of these two data also appeared to be less than that of nchr, but when I increased inflation, the ideal effect was finally achieved.
（2：triploid genome）This is using data from three tomato species, and then manually combining their read data and Hi-C to simulate triploids


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "zengxiaofei/HapHiC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月10日(星期三) 上午10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zengxiaofei/HapHiC]  the final number of groups was smaller than the nchrs I set. (Issue #35)





 
Some aspects that require further clarification or additional information:
 (1) Were the Hi-C data and the assembly obtained from the same individual? (tetraploid waxapple)
 (2) What methods (assembler and parameters) were used for genome assembly? Which assembly version was used for scaffolding (p_utg, p_ctg, or hap*.p_ctg)? Is the heterozygosity level of the genome sufficient for haplotype-phased assembly? (tetraploid waxapple)
 (3) How was data simulated for the triploid genome? Whether both the assembly and Hi-C reads simulated? What is the heterozygosity level of the simulated assembly? Which tool was used for Hi-C read simulation (e.g., sim3C)? Please provide details of the commands used.

**Comment by zengxiaofei** [comment]
> the Hi-C data and the assembly obtained is not from the same individual.

To perform haplotype-phasing, it is essential to use Hi-C data and assembly derived from either the same individual or individuals with identical genetic background (e.g., achieved through vegetative propagation).

> This is using data from three tomato species, and then manually combining their read data and Hi-C to simulate triploids.

Actually, I have validated and discussed this simulation strategy in the HapHiC paper. Based on my findings, I must emphasize that this method is not a good idea for simulating polyploids.

![simulation](https://github.com/zengxiaofei/HapHiC/assets/22426230/8dd7dd55-8568-4b3d-abb6-f9e7827b5d82)

**Supplementary Fig. 2** | Artificial merging of data from two rice subspecies, *indica* and *japonica*, leads to an underestimation of Hi-C links between homologous chromosomes. **a**, Ideally, the contigs between homologous chromosomes should be more difficult to separate than those between non-homologous chromosomes. **b**, However, the artificial merging of data from indica and japonica makes the contigs between homologous chromosomes easier to separate than those between non-homologous chromosomes in ALLHiC. **c**, This phenomenon can also be observed in HapHiC.

> "In the ALLHiC paper, the authors simulated a haplotype-resolved diploid genome by merging both the genome sequences and Hi-C data of two rice subspecies, indica and japonica1. However, this approach has some limitations. First, in a real diploid, there are background interactions between homologous chromosomes, because they are located in the same nucleus. The artificial merging of data from different subspecies leads to an underestimation of Hi-C links between homologous chromosomes, making it easier to separate them even than those between non-homologous chromosomes (Supplementary Fig. 2)."

Other concerns:

(1) Have the genome reads and Hi-C reads been normalized based on read depth?
(2) Do these genome reads from different species have similar sequencing error rates?

**Comment by zengxiaofei** [comment]
Close this issue as there has been no response for two weeks.
