### ISSUE TITLE
alternatives to Intel channel?

### ISSUE THREAD

**Issue by DiegoSafian** [zengxiaofei/HapHiC#38]
Hi,
I was wondering if there are alternatives to installing HipHiC without using the Intel channel. I am working in a cluster and I do not have permission to activate that channel. It should be possible to install mkl and others using other channels, but I prefer to ask because of version compatibility

Kind regards,
Diego

**Comment by zengxiaofei** [comment]
Hi Diego,

It's not a big problem. The Intel MKL is required for installing the Python module `sparse_dot_mkl`. Even if the Intel MKL and the Python library `sparse_dot_mkl` are not installed properly, HapHiC can still work by automatically detecting the environment and switching to dense matrix mode instead.

Best regards,
Xiaofei

**Comment by zengxiaofei** [comment]
Intel has removed its account on anaconda. I will fix this problem by updating a yml file as soon as possible.

**Comment by zengxiaofei** [comment]
I have updated the Conda environments for every Python version. I would appreciate it if you could give it a try.

**Comment by zengxiaofei** [comment]
Close this issue as there has been no response for two weeks.
