### ISSUE TITLE
I may have encountered some bugs due to the python version

### ISSUE THREAD

**Issue by Weihankk** [zengxiaofei/HapHiC#41]
Some bug like` subprocess.CalledProcessError .... returned non-zero exit status 1` may caused by python and packages version.

This error always occurs in the python3.10 environment and I guess is the matplotlib version from pip/conda caused. After I redeployed the environment according to the py312 method, there is no error and running successfully. I hope it can help other users.

**Comment by zengxiaofei** [comment]
I have updated the Conda environments for every Python version. I would appreciate it if you could give it a try.

**Comment by Weihankk** [comment]
I have tested the newly released conda yml based on py310 and py312 versions. The py312 version is normal, but py310 has errors related to pysam during installation. Therefore, I changed the pysam version in py310 yml to the same version 0.22.1 as py312, and the installation was successful. After subsequent tests, both versions ran without errors.

**Comment by zengxiaofei** [comment]
It's an issue of GCC version. Please use the py312 environment instead.
