### ISSUE TITLE
I encountered an issue during the installation of HapHic

### ISSUE THREAD

**Issue by wiltbb** [zengxiaofei/HapHiC#42]
I encountered an HTTP 000 error repeatedly when installing the software.Executive command "conda env create -HapHiC/conda_env/environment_py310.yml"

**Comment by zengxiaofei** [comment]
It could be a network issue. You may need to check whether the Conda server is accessible in your network. You could also try using a mirror, such as https://mirrors4.tuna.tsinghua.edu.cn/help/anaconda/?eqid=d6e48d3c0005a83700000006646e291f.

**Comment by zengxiaofei** [comment]
Close this issue as there has been no response for two weeks.
