### ISSUE TITLE
使用conda安装时报错 403 FORBIDDEN

### ISSUE THREAD

**Issue by zhang121a** [zengxiaofei/HapHiC#43]
您好，我在使用 
`conda env create -f HapHiC/conda_env/environment_py312.yml ` 为集群安装 HapHic 时出现了报错：
`Retrieving notices: ...working... done
Channels:
 - intel
 - conda-forge
 - defaults
 - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
 - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
Platform: linux-64
Collecting package metadata (repodata.json): failed

UnavailableInvalidChannel: HTTP 403 FORBIDDEN for channel intel <https://conda.anaconda.org/intel>

The channel is not accessible or is invalid.

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
`
为了能够成功安装，我尝试了使用micromanba，以及添加 "https://software.repos.intel.com/python/conda" ，但是都会出现相似的403报错，直接使用 micromamba 搜索 HapHic 也没有找到。

请问我该如何解决这个问题呢？

**Comment by zengxiaofei** [comment]
It's an issue caused by intel. Please update HapHiC to the latest version, I have fixed this problem by updating the .yml files.

**Comment by zhang121a** [comment]
Thank you so much for such a quick reply! 
I've successfully installed HapHic!
Also during the installation I encountered a situation where pip couldn't install pysam, but was able to find it with mamba, so I removed it from the yml file and installed pysam manually with mamba after successfully installing the rest of the parts. Will this have any impact? You didn't install directly with conda, which makes me wonder if there are other considerations.

**Comment by zengxiaofei** [comment]
> You didn't install directly with conda, which makes me wonder if there are other considerations.

Because I want to control the versions of all packages to maintain HapHiC's reproducibility and provide timely updates for them at the same time.

> Also during the installation I encountered a situation where pip couldn't install pysam, but was able to find it with mamba, so I removed it from the yml file and installed pysam manually with mamba after successfully installing the rest of the parts.

Could you please show me the error message?

**Comment by zengxiaofei** [comment]
> Also during the installation I encountered a situation where pip couldn't install pysam, but was able to find it with mamba, so I removed it from the yml file and installed pysam manually with mamba after successfully installing the rest of the parts.

It seems the issue could be related to having a low GCC version. Consider installing the environment for Python 3.11 instead.

**Comment by zhang121a** [comment]
Of course, the error message is so long and mixed with other outputs, and the final part I think is an error message like this:
`            gcc -pthread -B /public/work/env/mamba/envs/haphic/compiler_compat -fno-strict-overflow -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /public/work/env/mamba/envs/haphic/include -fPIC -O2 -isystem /public/work/env/mamba/envs/haphic/include -fPIC -I/tmp/pip-install-jdeo9wc9/pysam_7bf34e81219f453cada20a7807dce25c/pysam -I/tmp/pip-install-jdeo9wc9/pysam_7bf34e81219f453cada20a7807dce25c/htslib -I/tmp/pip-install-jdeo9wc9/pysam_7bf34e81219f453cada20a7807dce25c/samtools -I/tmp/pip-install-jdeo9wc9/pysam_7bf34e81219f453cada20a7807dce25c/samtools/lz4 -I/tmp/pip-install-jdeo9wc9/pysam_7bf34e81219f453cada20a7807dce25c/bcftools -I/tmp/pip-install-jdeo9wc9/pysam_7bf34e81219f453cada20a7807dce25c -I/public/work/env/mamba/envs/haphic/include/python3.12 -c pysam/libchtslib.c -o build/temp.linux-x86_64-cpython-312/pysam/libchtslib.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
      In file included from pysam/libchtslib.c:2154:0:
      /public/work/env/mamba/envs/haphic/include/python3.12/internal/pycore_frame.h: In function ‘_PyFrame_Initialize’:
      /public/work/env/mamba/envs/haphic/include/python3.12/internal/pycore_frame.h:134:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
           for (int i = null_locals_from; i < code->co_nlocalsplus; i++) {
           ^
      /public/work/env/mamba/envs/haphic/include/python3.12/internal/pycore_frame.h:134:5: note: use option -std=c99 or -std=gnu99 to compile your code
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pysam
Failed to build pysam
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pysam)
critical libmamba pip failed to install packages
`
I don't understand what this error message means, but it does seem to be related to GCC. I'll try to change the python version tomorrow.

**Comment by zhang121a** [comment]
> > Also during the installation I encountered a situation where pip couldn't install pysam, but was able to find it with mamba, so I removed it from the yml file and installed pysam manually with mamba after successfully installing the rest of the parts.
> 
> It seems the issue could be related to having a low GCC version. Consider installing the environment for Python 3.11 instead.

I'm sorry I was late in replying. After using python 3.11, the installation was successful, and no error was reported. Thanks again for your help!
