### ISSUE TITLE
Wrong assembly of X chromosome

### ISSUE THREAD

**Issue by gotouerina** [zengxiaofei/HapHiC#46]
I use haphic to anchor a genome to chromosome level but the results may be wrong. The X chromosome was not successfully assembled.

**Comment by zengxiaofei** [comment]
It's very normal. Current scaffolding tools cannot guarantee perfect results. Manual adjustment in Juicebox is typically necessary. In addition, there are also other reasons that may lead to poor results. For example, if you are scaffolding a haplotype-resolved assembly, the Hi-C depths of the Y chromosome and the non-PAR region on the X chromosome will be higher than those of autosomes, which can disrupt the clustering step during the scaffolding. In this case, you can refer to the parameters we used for the human genome HG002:

```bash
$ haphic pipeline <asm.fa> <filtered_HiC.bam> 46 --remove_allelic_links 2 --density_upper 1 --remove_concentrated_links --normalize_by_nlinks
```

**Comment by zengxiaofei** [comment]
Close this issue as there has been no response for two weeks.
