### ISSUE TITLE
Assemble a diploid genome based on Hi-C data from a tetraploid genome assembly

### ISSUE THREAD

**Issue by awesomedeer** [zengxiaofei/HapHiC#50]
Dear Zeng @zengxiaofei 
I have a chromosome-level tetraploid genome assembly which was scaffolded by Hi-C results.
I found in pulic data that a diploid individual was sequenced by long-reads sequencing but lack of Hi-C data.
Since I have seen the powerful scaffolding by **HapHiC**, I was wondering _**if I can use the Hi-C data from another study to scaffold a diploid genome**_ by reducing the parameters through mapping the HiC reads. etc? Although i's a bit beyond the purpose of this software, I bet you might have some good ideas!

Best regards
Song

**Comment by zengxiaofei** [comment]
If this diploid assembly is not haplotype-resolved (i.e., haplotype-collapsed or primary), it is acceptable to use Hi-C data from other individuals to scaffold this assembly. This approach is very similar to reference genome-based scaffolding. However, the results should be interpreted with caution.

**Comment by zengxiaofei** [comment]
Close this issue as there has been no response for two weeks.
