### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by DayTimeMouse** [zengxiaofei/HapHiC#51]
Hi,

1. When I run `bash juicebox.sh`, I get this error. Below is the detail:
juicebox.sh:
`ln -s /home/workdir/haphic/genome.fasta .`
`samtools faidx genome.fasta`
`/home/workdir/haphic/HapHiC/scripts/../utils/juicer pre -a -q 1 -o out_JBAT /home/workdir/haphic/HiC.filtered.bam scaffolds.raw.agp genome.fasta.fai >out_JBAT.log 2>&1`
`(java -jar -Xmx32G /home/workdir/haphic/HapHiC/scripts/../utils/juicer_tools.1.9.9_jcuda.0.8.jar pre out_JBAT.txt out_JBAT.hic.part <(cat out_JBAT.log | grep PRE_C_SIZE | awk '{print $2" "$3}')) && (mv out_JBAT.hic.part out_JBAT.hic)`
Log:
`Not including fragment map`
`Start preprocess`
`Writing header`
`Writing body`
`.Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded`
	`at java.io.BufferedOutputStream.<init>(BufferedOutputStream.java:76)`
	`at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.dumpBlocks(Preprocessor.java:1586)`
	`at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.incrementCount(Preprocessor.java:1570)`
	`at juicebox.tools.utils.original.Preprocessor$MatrixPP.incrementCount(Preprocessor.java:1389)`
	`at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:660)`
	`at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:346)`
	`at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:116)`
	`at juicebox.tools.HiCTools.main(HiCTools.java:96)`
But my Linux server has 1 terabyte of RAM.

2. Another question is, after geting the scaffolds through Haphic, how can I achieve chromosome-level assembly of the genome?

Best wishes.

**Comment by zengxiaofei** [comment]
1. See our note in the [Juicebox curation](https://github.com/zengxiaofei/HapHiC#juicebox-curation) section:
> For large genomes, it is necessary to adjust the memory settings in the juicebox.sh file for Java (e.g. set to `-Xmx64G` or higher) to avoid out-of-memory errors or to improve the execution speed.

2. In most cases, HapHiC can generate chromosome-level scaffolds. However, no scaffolders are able to guarantee perfect results at the moment. So, you need to verify this in Juicebox.

**Comment by DayTimeMouse** [comment]
Thanks. I modified the memory settings, then the program is running.

HapHiC can generate chromosome-level scaffolds. But how can I determine which scaffold belongs to which chromosome? Using minimap2? Or, do you have another ideas?

**Comment by zengxiaofei** [comment]
If there are reference genomes or genetic maps for this species, you can assign chromosome numbers to these scaffolds via genome-genome alignment (e.g., minimap2; we have provided a easy-to-use method called refsort to find their relationships and order and orient scaffolds automatically) or mapping the genetic markers to these scaffolds (e.g., bwa).

Otherwise, you can assign chromosome numbers yourself to these scaffolds based on their lengths.
