### ISSUE TITLE
some chromosomes were grouped together, or the maximum number of clusters is even less than the expected number of chromosomes. 

### ISSUE THREAD

**Issue by Xiaogongao** [zengxiaofei/HapHiC#55]
RuntimeError: Pipeline Abortion: Inflation recommendation failed. It seems that some chromosomes were grouped together, or the maximum number of clusters is even less than the expected number of chromosomes. For more details, please check out the logs.

**Comment by zengxiaofei** [comment]
Please see our [document](https://github.com/zengxiaofei/HapHiC), [FAQ](https://github.com/zengxiaofei/HapHiC#faqs) and [this issue](https://github.com/zengxiaofei/HapHiC/issues/32) before asking questions.

**Comment by Xiaogongao** [comment]
Sorry, I just noticed, thank you so much for your quick reply!
