### ISSUE TITLE
haphic plot

### ISSUE THREAD

**Issue by YaoZhou89** [zengxiaofei/HapHiC#6]
Hi Xiaofei,

When I used the haphic plot to generate the heatmap after manual curation, I found that the output was still the original. When I imported the reviewed assembly file into juicerbox, the heatmap kept unmodified as well. I checked the .assembly and .review.assembly files and both files are correct. Would you happen to know what's happening? 

Thanks in advance for your help!

Best regards,
Yao

**Comment by zengxiaofei** [comment]
Hi Yao,

Could you please upload these files: `scaffolds.raw.agp`, `out_JBAT.FINAL.agp`, `*.assembly`, `*.review.assembly` ?

Best,
Xiaofei

**Comment by YaoZhou89** [comment]
Hi Xiaofei,

Attached are the files requested. Thank you so much for your help!

Best regards,
Yao

[haphiic_plot.zip](https://github.com/zengxiaofei/HapHiC/files/13771950/haphiic_plot.zip)

**Comment by zengxiaofei** [comment]
Hi Yao,

Although I did not find any mistakes in your uploaded files, several users have reported an issue that Juicebox cannot correctly handle `*.review.assembly` when manual scale setting is required. One potential solution is to regenerate a `.hic` file using `juicer pre`.
However, `haphic plot` is expected to produce distinct heatmaps when dealing with `scaffolds.raw.agp` and `out_JBAT.FINAL.agp`. There might be a mistake in your command lines.

Best,
Xiaofei

**Comment by YaoZhou89** [comment]
Hi Xiaofei,

I found the problem. I should use the hic.filtered.bam instead of the contact_matrix.pkl when I changed the agp file. Thanks so much for your help!

Best regards,
Yao

**Comment by zengxiaofei** [comment]
Update: since the version 1.0.6, there is no longer a need to manually set the scale factor in Juicebox. In addition, the saved .review.assembly file can now be parsed correctly by Juicebox.
