### ISSUE TITLE
[E::bgzf_read] Read block operation failed with error 4 after 0 of 4 bytes samtools view: error reading file "HiC.bam" samtools view: error closing "HiC.bam": -1

### ISSUE THREAD

**Issue by cht-jk** [zengxiaofei/HapHiC#61]
Hello author：
（1）bwa mem -5SP -t 80 Six_genome.bp.p_ctg.fasta Q-6-Hi_c_1.clean.fq.gz Q-6-Hi_c_2.clean.fq.gz | samblaster | samtools view - -@ 80 -S -h -b -F 3340 -o HiC.bam
（2）/home/export/online3/caohaitao/HapHiC/haphic/HapHiC/utils/filter_bam HiC.bam 1 --nm 3 --threads 80 | samtools view - -b -@ 80 -o HiC.filtered.bam
The following error occurred while running step (2):
[E::bgzf_read] Read block operation failed with error 4 after 0 of 4 bytes
samtools view: error reading file "HiC.bam"
samtools view: error closing "HiC.bam": -1

**Comment by zengxiaofei** [comment]
I seems that your `HiC.bam` was not correctly generated. Please check the file using `samtools view HiC.bam`

**Comment by cht-jk** [comment]
haphic pipeline Six_genome.bp.p_ctg.fasta HiC.filtered.bam 25 --quick_view --RE "GATC" --correct_nrounds 2 --remove_allelic_links 4 --threads 60 --processes 60
Will the information indicated in the figure have an impact on the results?
![企业微信截图_17254998327187](https://github.com/user-attachments/assets/946493dd-d13c-48aa-9fa5-8a99baefcf44)

**Comment by zengxiaofei** [comment]
The `sparse_dot_mkl` module is only used to speed up the clustering step. It does not affect the results.

**Comment by cht-jk** [comment]
haphic reassign ../Six_genome.bp.p_ctg.fasta full_links.pkl mcl_inflation_4.2.clusters.txt paired_links.clm --nclusters 25
Running Reassign alone resulted in the following error
![image](https://github.com/user-attachments/assets/9d8d0294-b726-4d08-86c9-00c40026f9f7)
thanks！

**Comment by zengxiaofei** [comment]
File not found error.

**Comment by cht-jk** [comment]
Hello, I would like to use only Haphic to draw the HIC heatmap. Can I skip the mounted part and only obtain the HIC heatmap without changing the original genome?

**Comment by zengxiaofei** [comment]
Please see our note in the [Visualization](https://github.com/zengxiaofei/HapHiC#visualization) section.

**Comment by cht-jk** [comment]
Hello, thank you for your answer. Currently, I am only using Haphic to draw a heatmap and skipping mounting. The resulting heatmap does not meet expectations. What is the situation?
![image](https://github.com/user-attachments/assets/c3f06145-fbfb-4969-aae0-6e3b858a8815)

**Comment by zengxiaofei** [comment]
1. How did you align the Hi-C reads to the assembly and filter them?
2. Does the first column of the AGP file match the reference name of the BAM file for `haphic plot`?

**Comment by cht-jk** [comment]
（1）
$bwa mem -5SP -t 50 sweettea.racon.2.fa R._c_var._suavissimus-3_1.clean.fq.gz R._c_var._suavissimus-3_1.clean.fq.gz | samblaster | samtools view - -@ 50 -S -h -b -F 3340 -o HiC.bam
$filter_bam HiC.bam 1 --nm 3 --threads 35 | samtools view - -b -@ 35 -o HiC.filtered.bam
$mock_agp_file.py sweettea.racon.2.fa > sweettea.agp
$haphic plot sweettea.agp HiC.filtered.bam --bin_size 1000 --min_len 5 --threads 80
（2）
does the sixth column of the AGP file match the reference name of the BAM file exactly

**Comment by zengxiaofei** [comment]
You used the same file `R._c_var._suavissimus-3_1.clean.fq.gz` for both ends of the Hi-C reads.

**Comment by cht-jk** [comment]
Oh, I just realized. Thank you very much

**Comment by cht-jk** [comment]
How to split group3 into two parts, one green part named group3 and the other green part named group26，thanks.
![image](https://github.com/user-attachments/assets/5ec7bfd6-7377-487a-a411-e05b6f9450d4)

**Comment by zengxiaofei** [comment]
https://github.com/aidenlab/Juicebox
https://github.com/zengxiaofei/HapHiC#juicebox-curation
