### ISSUE TITLE
loss centromere contacts

### ISSUE THREAD

**Issue by PengfeiInTuebingen** [zengxiaofei/HapHiC#62]
Hi, 
Very cool and easy to use tool for hi-c scaffolding!
Based on the idea of centromere-to-centromere clustering, when i was doing manually curation for my genome, seems like i lost one of centromere interactions for a chromosome, attached is the plot, could you please comment on this?
<img width="917" alt="image" src="https://github.com/user-attachments/assets/5645cc2c-5533-4523-b743-473336e0e5ca">

Best,
PF

**Comment by zengxiaofei** [comment]
Maybe the centromere of this chromosome was not successfully assembled or anchored.

**Comment by zengxiaofei** [comment]
Close this issue as there has been no response for two weeks.
