### ISSUE TITLE
Sequence lost after Juicebox curation

### ISSUE THREAD

**Issue by lancelot-bio** [zengxiaofei/HapHiC#63]
Hi,
After scaffolding, I followed the recommendation, executed the juicebox.sh, and used the out_JBAT.hic and out_JBAT.assembly to obtain a modified assembly in juicebox.
However, when I ran the juicer post command, it posted an error:
`[E::make_asm_dict_from_agp] sequence ptg000032l not found`
I checked other files, 'ptg000032l' was presented in related files but the out_JBAT.review.assembly file.
Is this error raised due to the changed name in out_JBAT.assembly?

Thanks

**Comment by zengxiaofei** [comment]
Please show me your commands.

**Comment by lancelot-bio** [comment]
Hi,
for haphic:
`~/01_Tools/HapHiC/haphic pipeline  filtered.curated.fasta HiC.filtered.bam 10 --threads 88 --skip_allhic --correct_nrounds 2`

for juicer.sh:
`ln -s ~/01_PrimaryContig/test_Haphic/filtered.curated.fasta .
samtools faidx filtered.curated.fasta
~/01_Tools/HapHiC/scripts/../utils/juicer pre -a -q 1 -o out_JBAT ~/01_PrimaryContig/test_Haphic/HiC.filtered.bam scaffolds.raw.agp filtered.curated.fasta.fai >out_JBAT.log 2>&1
(java -jar -Xmx32G ~/01_Tools/HapHiC/scripts/../utils/juicer_tools.1.9.9_jcuda.0.8.jar pre out_JBAT.txt out_JBAT.hic.part <(cat out_JBAT.log | grep PRE_C_SIZE | awk '{print $2" "$3}')) && (mv out_JBAT.hic.part out_JBAT.hic)`

for juicer post:
`~/01_Tools/HapHiC/utils/juicer post -o out_JBAT  out_JBAT.review.assembly out_JBAT.liftover.agp scaffolds.fa`

Thanks.

**Comment by zengxiaofei** [comment]
The command for `juicer post` should be:

~/01_Tools/HapHiC/utils/juicer post -o out_JBAT  out_JBAT.review.assembly out_JBAT.liftover.agp filtered.curated.fasta

**Comment by lancelot-bio** [comment]
Hi, 
Ye, I found the problem, and it posted another error:
`[E::assembly_to_agp] coordinates conversion error ptg000032l 0`
Here is my agp and assembly file:
[out_JBAT.zip](https://github.com/user-attachments/files/16940148/out_JBAT.zip)
Thanks.

**Comment by zengxiaofei** [comment]
The contig IDs in the assembly file should start with `ctg` (contig names converted by juicer pre). However, the first 18 contig IDs start with `ptg` (original contig names). Did you modify the assembly file yourself?

**Comment by lancelot-bio** [comment]
Hi,
Yes, when I realized the problem may related to the name, I tried to modify them, and, eventually, I forgot to reverse these actions.

Many thanks.

**Comment by Isoris** [comment]
I woud like to ask you too because I have generated the files with the --quick_mode and so It seems I encountered the same error as you. 

Do you think that I could yahs/agp_to_fasta.py into juicer post -a ? 

Thank you for the answer.
Quentin

**Comment by Isoris** [comment]
It seems to be related to how we load the assemblies in JBAT because my scaffolds went from ctg to group1 because I have used a custom script to get the green contig bins maybe the other people did too or did you solve it  ?

**Comment by Isoris** [comment]
I solved it using the script in the juicebox_scripts/ folder. Thanks again

**Comment by bl24** [comment]
@Isoris Hi, I'm running into this same issue. What script did you end up using?

**Comment by Isoris** [comment]
So what your have to do is to go into the yahs directory and there will be
a ditectory juicebox scripts and inside another juicebox scripts

Then in this directory there is like generate fasta from assembly or
something like that. You need to first generate the agp  file of your
sequence. then the contig names should match the assembly file contig names
and then you can generate the fasta... Let me search it again for you. I
don't remember precisely...

**Comment by Isoris** [comment]
But that worked because I renamed the contigs of the assembly file of juicebox manually with sed prior to using the convert to fasta script. And I could guess the names of the scaffold from their order because I didn't move them (reorder them like 1 2 3 4) but I kept the order of the Blue scaffold intact as in the initial ( non reviewed) assembly file. This way I could rename the reviewed file with the names in ghe AGP file. And use both to make the fasta.

**Comment by bl24** [comment]
Are you referring to juicebox_assembly_converter.py? If found that from the juicebox_scripts repository: https://github.com/phasegenomics/juicebox_scripts

**Comment by bl24** [comment]
I did try it but I get this error: 

Checking for breaks listed in .assembly and making them...
Traceback (most recent call last):
  File "/wing2/users/bmlau/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 872, in <module>
    processed_assembly = JuiceboxConverter().process(fasta, assembly,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/wing2/users/bmlau/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 91, in process
    sequences = self._add_breaks(sequences, assembly_map)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/wing2/users/bmlau/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 300, in _add_breaks
    raise BadContigNameError("Unbroken contig {} failed to map!!".format(fragment_name))
BadContigNameError: Unbroken contig ctg00000001.1 failed to map!!

**Comment by Isoris** [comment]
The names of your contigs in your fasta should be the same as in Your
assembly file

**Comment by Isoris** [comment]
Compare the initial assembly file ( before juicebox) to the final review
file.
Are the names matching ? Next are the review file contig names the same as
the review assembly file ?

Next, remove lines in the final review file that have debris on it. And
lines that end with 0 change to 1  to indicate its 1 nucleotide long for
the contig and not 0 ( sometimes Juicebox can bug and when you cut at a
certain zoom and have the camera locked it will cut the contig and generate
a small contig that has a length of 0... )

**Comment by bl24** [comment]
Okay, I removed the debris but then it gave me a different error:
MissingFragmentError: Assembly out_JBAT.review2.assembly is missing the sequence for index 19

I'm confused about the contigs in my fasta needing to be the same as the assembly. Isn't the purpose of the liftover.agp file to have a conversion between the assembly and the fasta? I ask because I've able to make juicer post work on other assemblies that didn't use quick_mode.

**Comment by Isoris** [comment]
Put nack the debris lines and the lines that you removed and make sure that
the contig names in the scaffold.assembly ( before juicebox ) are the same
as the .review.assembly

And the same as the fasta

Yes there's a bug that breaks the review file when we add fragments let me
check my bash History

**Comment by bl24** [comment]
Comparing my original assembly with my review assembly and I noticed there are also things labeled "fragments" in my review file

>ctg00000018.1:::fragment_1 18 2575032
>ctg00000018.1:::fragment_2:::debris 19 775000
>ctg00000018.1:::fragment_3 20 424305
>ctg00000019.1:::fragment_1 21 237691
>ctg00000019.1:::fragment_2:::debris 22 375000
>ctg00000019.1:::fragment_3 23 7350695

**Comment by Isoris** [comment]
I don't understand why you have debris ? In my opinion you can maybe try to
remove chromosome boundaries and then move to debris?

Like in JBAT the debris are the unwanted contigs.
Usually you remove the chromosome boundaries ?

The convert script cannot accomodate with the :::debris I think.

Thats why I cannot really cut and rebuild thr fasta it's like a bug?

**Comment by Isoris** [comment]
But that worked because I renamed the contigs of the assembly file of juicebox manually with sed prior to using the convert to fasta script. And I could guess the names of the scaffold from their order because I didn't move them (reorder them like 1 2 3 4) but I kept the order of the Blue scaffold intact as in the initial ( non reviewed) assembly file. This way I could rename the reviewed file with the names in ghe AGP file. And use both to make the fasta.

**Comment by Isoris** [comment]
Here is what my .review file looks file 

![IMG_20241108_035515.jpg](https://github.com/user-attachments/assets/0173b280-9685-4935-bf12-08c90d8a2ed7)

![IMG_20241108_035529.jpg](https://github.com/user-attachments/assets/d9befc2b-9c35-4d6c-984d-a32cad153541)

**Comment by Isoris** [comment]
> Comparing my original assembly with my review assembly and I noticed there are also things labeled "fragments" in my review file
> 
> >ctg00000018.1:::fragment_1 18 2575032
> >ctg00000018.1:::fragment_2:::debris 19 775000
> >ctg00000018.1:::fragment_3 20 424305
> >ctg00000019.1:::fragment_1 21 237691
> >ctg00000019.1:::fragment_2:::debris 22 375000
> >ctg00000019.1:::fragment_3 23 7350695
> 

The fragments in the review file are normal they are the green contigs squares in Juicebox. While the contigs ( on the left ) are the blue scaffolds in juicebox.

Your file seems normal. And what about your fasta ? 

Can you grep the header names?

**Comment by Isoris** [comment]
It's probably a matter of names or maybe it's related to the .1 ? After ctg ?
Or maybe becauae your first contig has a problem or no fragment or ? Can you please show the top of your .review file?

Also maybe you need to change the file to 

>ctg instead of ctg

> I did try it but I get this error: 
> 
> Checking for breaks listed in .assembly and making them...
> Traceback (most recent call last):
>   File "/wing2/users/bmlau/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 872, in <module>
>     processed_assembly = JuiceboxConverter().process(fasta, assembly,
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/wing2/users/bmlau/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 91, in process
>     sequences = self._add_breaks(sequences, assembly_map)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/wing2/users/bmlau/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 300, in _add_breaks
>     raise BadContigNameError("Unbroken contig {} failed to map!!".format(fragment_name))
> BadContigNameError: Unbroken contig ctg00000001.1 failed to map!!

**Comment by bl24** [comment]
Okay, I realize the reason why I was getting errors is because I was using a different fasta file. Instead of using the original fasta input for the HapHic pipeline I used the corrected_asm.fa for quick_view mode after the pipeline gave me the message: 

"It seems that some chromosomes were grouped together (length ratio = 0.5) You could check whether the parameters used are correct / appropriate and then try to tune the parameters for assembly correction, contig / Hi-C link filtration, or Markov clustering"

**Comment by ChengQin01** [comment]
Hi,
Could you please clearly  clarify `filtered.curated.fasta` ？Can I regard it as hap1/2.p_ctg.fa?

@zengxiaofei 




> The command for `juicer post` should be:
> 
> ~/01_Tools/HapHiC/utils/juicer post -o out_JBAT out_JBAT.review.assembly out_JBAT.liftover.agp filtered.curated.fasta

**Comment by zengxiaofei** [comment]
Hi @ChengQin01,

`filtered.curated.fasta` is not the standard name we use in the documentation. Please always refer to our documentation (in fact, if HapHiC and Juicebox are used correctly, the issue mentioned will not occur):

> ```
> # Generate the final FASTA file for the scaffolds
> $ /path/to/HapHiC/utils/juicer post -o out_JBAT out_JBAT.review.assembly out_JBAT.liftover.agp asm.fa
> ```

Here, `asm.fa` refers to the FASTA file that is input into HapHiC, and it is also the reference genome to which the Hi-C data is aligned. You just need to ensure that they are the same file. (I have ensured that its file name is consistent throughout the documentation.)

**Comment by ChengQin01** [comment]
OK, thanks for your fast and clear stat.
