### ISSUE TITLE
Haplotype inference on polyploids 

### ISSUE THREAD

**Issue by Rhia15** [zengxiaofei/HapHiC#68]
Hi, I am currently manually curating a a tetraploid genome in Pretextview which I assembled with HapHic, I am just wondering how you would infer the haplotypes from the HiC contact map? I understand there's a picture from refsort of a tetraploid: 
<img width="501" alt="image" src="https://github.com/user-attachments/assets/5457d744-e55f-40b2-95d4-e5d1667dda24">

I assumes that within each larger square, scaf1, scaf2, scaf3, scaf4 would equal to Hap1, Hap2, Hap3, Hap4 and so on? Or is this not the case? 

For example, this is a snippet of my current assembly on PretextView, and I have just assumed that these are the Haplotypes: 
<img width="867" alt="image" src="https://github.com/user-attachments/assets/46c880f2-f301-4f56-be50-2d2692af9541">

Any advice on haplotype inference from the HiC contact map would be great!

Thank you very much!

**Comment by zengxiaofei** [comment]
Typically, diagonally distributed Hi-C signals can be found between homologous chromosomes. These Hi-C links result from base-level switch errors during genome assembly and Hi-C read mapping errors. Although they do not represent true chromatin interactions, this information can still be used to infer haplotypes. In your case, these diagonally distributed Hi-C links are also present. However, this pattern may not be observed when the heterozygosity level is too high. To address this issue, haplotypes can be inferred through self-alignment or by aligning the assembly to a reference genome. In your case, I’m not sure how you performed Hi-C read mapping and filtering. In addition, I’m not sure how these Hi-C links are normalized and visualized. However, it is clear that there are many errors in the assembly.

**Comment by Rhia15** [comment]
Hi thank you so much for the quick response, I was wondering if you would please be able to point out the errors, I can't seem to find many resources for polyploid Hi-C maps and I'd love to learn more. Are the errors present in the way I have arranged the Hi-C map or do they stem from pre processing? How did you spot these errors? 

I mapped them using samtools and then started rearranging in pretextview, do you recommend using HapHic assembies with Juicebox instead of other tools such as PretextView? 
![image](https://github.com/user-attachments/assets/79d958ab-3514-4fd7-b1ee-8f7f88bb5d3e)

Thank you so much!!

**Comment by zengxiaofei** [comment]
When using `bwa mem` to align Hi-C reads, I would recommend added the `-5SP` flag. Here is the description of these parameters from Phase Genomics:

> We use bwa mem to align Hi-C data, with the -5, -S, and -P options. These options aren’t documented that well in the online bwa documentation, but they are documented in the usage of bwa mem. -5 is sometimes called “the Hi-C option” as it was designed to help the aligner handle the statistical properties of Hi-C libraries better, mainly by reducing the amount of secondary and alternate mappings the aligner makes as those cause Hi-C data to become ambiguous. The -S and -P options cause the aligner not to try to use assumptions about the reads that might be true for shotgun or mate pair libraries in an effort to rescue more reads. In fact, using these options to avoid those rescue efforts usually results in more of the Hi-C data having a useful alignment!

In addition, I also recommend filtering the `align.bam` with the MAPQ>=1 criterion. Without MAPQ filtering, there will be too many mapping errors in the contact map.

> I was wondering if you would please be able to point out the errors, I can't seem to find many resources for polyploid Hi-C maps and I'd love to learn more. Are the errors present in the way I have arranged the Hi-C map or do they stem from pre processing? How did you spot these errors?

Scaffolding a polyploid genome is a complex task influenced by various factors. These include intrinsic genomic characteristics like heterozygosity and the distribution of heterozygous loci, the quality of contig assembly, the methods used for Hi-C read alignment and filtering, and the parameters set in HapHiC. Currently, I am not clear about these specific details, so I cannot draw a conclusion.

When comparing haplotype-resolved and haplotype-collapsed assemblies, the contact map within a chromosome typically shows no differences. However, between chromosomes, switch errors and Hi-C read mapping errors often result in diagonally distributed Hi-C links. These Hi-C signals, aside from truth structural variations between haplotypes, generally run parallel to each other. In your case, Scaffold 13 contains a redundant sequence that should be relocated to Scaffold 15 or 16. Similarly, Scaffold 17 has a redundant region. Additionally, both Scaffold 15 and 16 appear to have missing regions, making them too short. The lack of diagonally distributed Hi-C signals between Scaffold 20 and Scaffolds 17-19 suggests that Scaffold 20 may not be the corresponding Hap4. For further details, I recommend referring to the contact map for refosort above, as it serves as a good example. Moreover, numerous articles on haplotype-resolved assembly have been published in recent years, and their contact maps may also be worth reviewing.

**Comment by zengxiaofei** [comment]
Close this issue as there has been no response for two weeks.
