### ISSUE TITLE
Does the haphic suitable for the Dovetail OmniC extraction?

### ISSUE THREAD

**Issue by Jimingliu60** [zengxiaofei/HapHiC#71]
Hi. Thanks for introducing such a wonderful hic assembly tool. However, there are some users are using the OmniC extraction kit, which use the Dnase as the restriction enzyme. Is the haphic suitable for the OmniC? And how should we run it?

Thanks.

**Comment by zengxiaofei** [comment]
I have previously answered a similar question on GitHub, you can view my response at: https://github.com/zengxiaofei/HapHiC/issues/10
