### ISSUE TITLE
zsh: permissionned denied

### ISSUE THREAD

**Issue by Axze-rgb** [zengxiaofei/HapHiC#75]
Hello,

Trying to install but getting this error

```
/home/alessandro/mambaforge/envs/haphic check
zsh: permission denied: /home/alessandro/mambaforge/envs/haphic
```

I am usually use mamba hence the mambaforge, but the error first appeared with a mamba installed so I removed it and tried to install with conda, but no difference. Any idea? I realize that might be a conda bug and not a haphic bug I hope I am not bothering you for nothing guys.

Thanks

Edit: note that 

`HapHiC/haphic`

doesn't exist in my installation

**Comment by zengxiaofei** [comment]
Hi @Axze-rgb,

Conda or mamba is only used to solve the dependencies for HapHiC. You need to execute the `haphic` script you downloaded by using `git clone`:

```bash
$ git clone https://github.com/zengxiaofei/HapHiC.git
# after that, navigate to the HapHiC directory to find the haphic script
$ cd HapHiC
$ ./haphic check
```

The script should be executable with a permission mode of 755. If you still encounter the error message 'permission denied,' please try changing the script's mode by using:

```bash
$ chmod 755 haphic
```

Best regards,
Xiaofei

**Comment by Axze-rgb** [comment]
Ohhhh, ok, I hadn't understood properly, sorry. Thanks for the answer it works.
