### ISSUE TITLE
haphic pipeline: error: argument nchrs: invalid int value: 'nchrs'

### ISSUE THREAD

**Issue by Axze-rgb** [zengxiaofei/HapHiC#76]
Hello,

I am really sorry, actually I feel embarrassed to ask again a question but when I do 

`~/software/HapHiC/haphic pipeline AV21_12.fasta HiC.bam nchrs 12 --threads 8 --processes 8 --correct_nrounds 2
`
I get

```
haphic pipeline: error: argument nchrs: invalid int value: 'nchrs'
Traceback (most recent call last):
  File "/home/alessandro/software/HapHiC/haphic", line 117, in <module>
    subprocess.run(commands, check=True)
  File "/home/alessandro/mambaforge/envs/haphic/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/alessandro/software/HapHiC/scripts/HapHiC_pipeline.py', 'AV21_12.fasta', 'HiC.bam', 'nchrs', '12', '--threads', '8', '--processes', '8', '--correct_nrounds', '2']' returned non-zero exit status 2.
```
but I have 12 chromosomes, how is it an invalid integer value?

Sorry again for the question and thanks so much for your patience, it's greatly appreciated.

**Comment by zengxiaofei** [comment]
Correct command should be:

```
~/software/HapHiC/haphic pipeline AV21_12.fasta HiC.bam 12 --threads 8 --processes 8 --correct_nrounds 2 
```

**Comment by Axze-rgb** [comment]
OK so nchrs is a simple "placeholder". I feel very stupid not having understanding that. May I make a suggestion, that you indicate it's a place holder by putting it under square brackets for example? It's usually how I am used to see placeholders. Just a little suggestion, you don't have to follow if I am the only one to have only ever asked that question. Again, thanks for you patience. Do you have a "pay me a coffee" or something? because I think you would deserve one. Thanks again. And also for your reactivity.

**Comment by Axze-rgb** [comment]
Yes it's precisely because I had the feeling (not very pleasant) I had misunderstood something obvious I wanted a way to apologise sincerely for losing your time with a stupid question. But anyway, it's sure you will gain a new citation if my paper is published as the scaffolding produced by HapHic will be the centre of everything. 

Once again I apologise, retrospectively I don't understand why I didn't get it was a placeholder.

**Comment by zengxiaofei** [comment]
Don't worry, it's okay. Please don't feel bad about it. :relaxed:

**Comment by Axze-rgb** [comment]
Thank you :)
