### ISSUE TITLE
absence of correlation between HiC contacts and generated assembly file for manual curation

### ISSUE THREAD

**Issue by dabitz** [zengxiaofei/HapHiC#8]
Dear all,

Thank you for the nice tool. I am trying to scaffold a very complex polyploid genome (expected hexaploid with around 66 chromosomes). Despite the challenge genome, haphic can group the expected number of scaffolds based on the HiC map, however, the generated agp and assembly files do not seem to match the HiC contacts observed. Now, I am not sure if there are a lot of misassemblies that need to be corrected or if there is something wrong with the outputs of haphic. Please see 
[2024.01.11.13.24.49.HiCImage.pdf](https://github.com/zengxiaofei/HapHiC/files/13903317/2024.01.11.13.24.49.HiCImage.pdf)
the attached files.
[Uploading 2024.01.11.13.26.22.HiCImage.pdf…]()

[2024.01.11.13.23.45.HiCImage.pdf](https://github.com/zengxiaofei/HapHiC/files/13903313/2024.01.11.13.23.45.HiCImage.pdf)
[2024.01.11.13.24.23.HiCImage.pdf](https://github.com/zengxiaofei/HapHiC/files/13903314/2024.01.11.13.24.23.HiCImage.pdf)

**Comment by zengxiaofei** [comment]
Hi @dabitz,

It seems to be an issue caused by the scale factor. Please set the scale manually in Juicebox after importing the `.assembly` file.

> Note: In the output log file `out_JBAT.log` , you can find the corresponding scale factor, e.g., `[I::main_pre] scale factor: 2` . To ensure proper alignment of Hi-C contact maps with the boundaries of scaffolds and superscaffolds in Juicebox, please set your own scale factor in Juicebox through the menu `Assembly > Set Scale` .

Best regards,
Xiaofei

**Comment by dabitz** [comment]
thanks a lot!

**Comment by dabitz** [comment]
It has worked pretty nice so far. The only thing is that when I save the review.assembly and try to reopen it later on to make additional changes it doesn't seem to store the modifications, although the newly generated fasta using the same review.assembly does have the modifications. Would have any idea why this is happening? I have tried different versions of juicebox with similar results. Thanks for any help on this!

**Comment by zengxiaofei** [comment]
Hi @dabitz,

Sorry for the delay. We have noticed the issue that Juicebox cannot correctly handle `.review.assembly` when manual scale setting is required. One solution is to regenerate a new `.hic` file using `juicer post` and `juicer pre`.

(1) Using `juicer post`, you can generate an AGP file named `out_JBAT.FINAL.agp` based on your `.review.assembly` file:

```bash
# out_JBAT.review.assembly: the .review.assembly file generated by Juicebox after manual curation
# out_JBAT.liftover.agp: an AGP file that was generated during executing juicebox.sh
/path/to/HapHiC/utils/juicer post -o out_JBAT out_JBAT.review.assembly out_JBAT.liftover.agp asm.fa
```

(2) Then, use `juicer pre` to regenerate a new `.hic` file for the next review in Juicebox:

```bash
# out_JBAT.FINAL.agp: the AGP file generated in the previous step
# asm.fa.fai: a FASTA index file that was generated during executing juicebox.sh
/path/to/HapHiC/utils/juicer pre -a -q 1 -o next_review /path/to/HiC.filtered.bam out_JBAT.FINAL.agp asm.fa.fai >next_review.log 2>&1
(java -jar -Xmx32G /path/to/HapHiC/utils/juicer_tools.1.9.9_jcuda.0.8.jar pre next_review.txt next_review.hic.part <(cat next_review.log | grep PRE_C_SIZE | awk '{print $2" "$3}')) && (mv next_review.hic.part next_review.hic)
```

Best regards,
Xiaofei

**Comment by zengxiaofei** [comment]
Update: since the version 1.0.6, there is no longer a need to manually set the scale factor in Juicebox. In addition, the saved .review.assembly file can now be parsed correctly by Juicebox.
