### ISSUE TITLE
Installing this HapHic process is so troublesome, it keeps giving errors. I'm really fed up with this software.

### ISSUE THREAD

**Issue by daixiahu123456** [zengxiaofei/HapHiC#82]
安装这个HapHic   流程好麻烦   一直报错    写的软件真的服了

ChatGPT translation: Installing this HapHic process is so troublesome, it keeps giving errors. I'm really fed up with this software.

**Comment by zengxiaofei** [comment]
If you are just venting your emotions, I cannot provide any help to you.

**Comment by zengxiaofei** [comment]
I will close this issue. If you would like to provide relevant information and engage in polite communication, you can choose to reopen it.
