### ISSUE TITLE
Can HapHiC support multiple BAM input ？

### ISSUE THREAD

**Issue by ChengQin01** [zengxiaofei/HapHiC#84]
Hello,
Thank you for developing the useful tool. I have a question about its input.
My HiC data was saved in multiple FASTA, which means multiple BAM would be generated while aligning to Ref. Can HapHic support multiple BAM file as inputs? Or I have to merge the HiC data before align to  ensure only one BAM would be generated?

**Comment by zengxiaofei** [comment]
> My HiC data was saved in multiple FASTA

You mean FASTQ, right?

> Can HapHic support multiple BAM file as inputs?

HapHiC does not support multiple BAM files as input now.

> Or I have to merge the HiC data before align to ensure only one BAM would be generated?

There is also another choice, merging the BAM files using `samtools merge`.

**Comment by zengxiaofei** [comment]
Close this issue as there has been no response for two weeks.
