### ISSUE TITLE
how to  simulate Hi-C data？

### ISSUE THREAD

**Issue by Yichen-HNU** [zengxiaofei/HapHiC#89]
Hello Zeng Xiaofei! Thank you for providing such an excellent tool.

However, I encountered some issues while following the simulation process for Hi-C data that you described in your work.

Following the workflow you provided in the attachments, I used the sim_contigs.py and sim_haplotypes.py scripts to generate multiple haplotype reference sequences. Assuming that I don't need to consider chimeric reads, I should use the multiple haplotypes generated by sim_haplotypes.py as inputs for sim3C to simulate Hi-C data. However, during the usage of sim3C, there are multiple options to choose from, such as the "Community Profile" or the default abundance distribution like --dist uniform. I would like to know how you choose among these options or if you could provide your complete workflow for simulating Hi-C data. I would greatly appreciate it!

**Comment by zengxiaofei** [comment]
Hello Yichen,

I have provided detailed commands in [Supplementary Information](https://static-content.springer.com/esm/art%3A10.1038%2Fs41477-024-01755-3/MediaObjects/41477_2024_1755_MOESM1_ESM.pdf) (**Software commands** > **1 Simulation of datasets for evaluating scaffolding tools** > **1.5 Simulation of datasets with different sequence divergences and ploidies**):

```bash
$ sim3C <haps.fa> <sim.fq> --profile ./mycom.txt -n <npairs> --efficiency 0.9 --trans-rate <rate> --anti-rate 0 -l 150 -e MboI -m hic --seed <seed> --machine-profile HiSeqXtruSeqL150
```

All parameters that are not mentioned in the command, like `--dist`, were not set in our simulation process.

As for the community profile, i.e., `mycom.txt` we used in our simulation, is a text file like:

```
#chrom    cell     molecule      abundance    copy_number
chr1_1   cellA   chromosome    1           1
chr1_2   cellA   chromosome    1           1
chr1_3   cellA   chromosome    1           1
chr1_4   cellA   chromosome    1           1
chr2_1   cellA   chromosome    1           1
chr2_2   cellA   chromosome    1           1
chr2_3   cellA   chromosome    1           1
chr2_4   cellA   chromosome    1           1
...
```

This file has also been described in [Supplementary Information](https://static-content.springer.com/esm/art%3A10.1038%2Fs41477-024-01755-3/MediaObjects/41477_2024_1755_MOESM1_ESM.pdf):

> where “mycom.txt” is the community profile file indicating that all chromosomes are located in the same cell with equal abundance and copy numbers set to 1.

We also have provided other useful information in this section to help you understand how we performed the simulation process:

> The parameters “-n” and “--trans-rate” were dynamically adjusted according to different ploidies to maintain a fixed intensity of intra- and inter-chromosome Hi-C links, as listed in Supplementary Table 9. To save time, the command was executed using ten parallel jobs with different seeds.

Best regards,
Xiaofei

**Comment by Yichen-HNU** [comment]
Dear Zeng Xiaofei,

Thank you for your prompt and detailed reply. I truly appreciate your guidance and the time you took to assist me.

Best regards,
Yichen
