### ISSUE TITLE
Is there a way to extract hic reads for binning ?

### ISSUE THREAD

**Issue by Isoris** [zengxiaofei/HapHiC#90]
Hello Xiaofei,
I would like to ask if after a P utg assembly with HapHiC would it be possible to extract the mapped hic reads selectively for Hap1 and Hap2?

For future downstream applications ? maybe from the clusters of HapHiC or the groups? I am not specialist but do you know any way or how we could achieve that ? ( To extract all reads mapped to a group in HapHiC from the initial HiC_filtered.bam )

Thank you in advance. 
Quentin.

**Comment by zengxiaofei** [comment]
You can filter your BAM file using `awk` with the command like:

```
samtools view your.bam | awk '($3=="chr1_1"||$3=="chr2_1"||$3=="chr3_1")&&($7=="="||$7=="chr1_1"||$7=="chr2_1"||$7=="chr3_1")'
```

**Comment by Isoris** [comment]
Thanks a lot. Have a great day.
