### ISSUE TITLE
consult

### ISSUE THREAD

**Issue by casusr** [zengxiaofei/HapHiC#91]
May I ask, I used the command samtools view -\@4 -f 4 -f 256-bq 20 to filter the bam file and generate the uniq.bam file? Then use the haphic pipeline p_ctg.fa uniq.bam 40 --RE GATC command and run bash juicebox.sh in the result, out_JBAT.txt does not exist or does not contain any reads

**Comment by zengxiaofei** [comment]
You may have misunderstood the meaning of the `-f` parameter in `samtools view`:

``
-f INT   only include reads with all of the FLAGs in INT present
```

If you do not have any specific requirements, I would recommend following the method provided in our documentation.

**Comment by casusr** [comment]
Sorry, I made a mistake. The samtools command I used was

`samtools view -\@4 -F 4 -F 256 -bq 20  `

is this also not acceptable？

**Comment by zengxiaofei** [comment]
The filtering process can result in singleton reads, which might cause some problems in downstream analyses. In addition, I am uncertain if setting `-bq 20` would be too stringent for your specific scenario. Therefore, I recommend starting with the method provided in our documentation, as it has proven effective in most cases.

**Comment by casusr** [comment]
Thank you very much for your answer
