### ISSUE TITLE
creating fasta file after refsort

### ISSUE THREAD

**Issue by Zhenlisme** [zengxiaofei/HapHiC#92]
Hello Xiaofei,

Thank you so much for this wonderful software.
I wanna know how I can get the re-ordered fasta file after finalizing the haphic refsort pipeline, which only outputs the .agp file. Do you have any suggestions?

Thanks a lot.

Best,
Zhen

**Comment by zengxiaofei** [comment]
Hi Zhen,

You can generate the corresponding FASTA file using the scripts for Juicebox visualization (for more information, please refer to https://github.com/zengxiaofei/HapHiC#juicebox-curation):

* **Method 1**

Use this method only If `--correct_nrounds` was not set. Please note that the [Juicebox scripts](https://github.com/phasegenomics/juicebox_scripts) should already be installed):

```bash
# Convert the .agp file to the .assembly file
/path/to/juicebox_scripts/agp2assembly.py scaffolds.refsort.agp scaffolds.assembly
# Generate the FASTA file. asm.fa is the contig-level FASTA file.
/path/to/juicebox_scripts/juicebox_assembly_converter.py -a scaffolds.assembly -f asm.fa -s
```

* **Method 2**

This method is compatible with files generated whether or not `--correct_nrounds` was set.

Please check out the commands in `04.build/juicebox.sh`. You can execute the first three commands in a new directory after replacing `scaffolds.raw.agp` with `scaffolds.refsort.agp`, like:

```bash
ln -s /path/to/asm.fa .
samtools faidx asm.fa
# This command will generate several files with the prefix 'out_JBAT'. Once out_JBAT.assembly has been fully generated, you can terminate the command (there's no need to wait for the generation of out_JBAT.txt, which can be slow)
/path/to/HapHiC/utils/juicer pre -a -q 1 -o out_JBAT /path/to/HiC.filtered.bam scaffolds.refsort.agp asm.fa.fai >out_JBAT.log 2>&1
```

After completing these steps, you can run `juicer post` to obtain the final FASTA file:

```bash
/path/to/HapHiC/utils/juicer post -o out_JBAT out_JBAT.assembly out_JBAT.liftover.agp asm.fa
```

Best regards,
Xiaofei

**Comment by Zhenlisme** [comment]
Thank you !
